- name: Install cloud packages
  aur:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: aur_builder
  with_items:
  - aws-cli
  - minikube
  - kubectl
  - tfenv
  - helm
- name: Make sure we have a 'tfenv' group
  group:
    name: tfenv
    state: present
- name: Add user '{{ create_user }}' to 'tfenv'
  user:
    name: "{{ create_user }}"
    groups:
    - tfenv
    append: yes
  become: true