- name: Install arkade
  shell: >
    curl -sLS https://dl.get-arkade.dev | sudo sh
  become: yes
  become_user: aur_builder
  args:
    creates: "/usr/local/bin/arkade"
- name: "Install ark packages version {{ item }}"
  shell: >
    arkade get {{ item }}
  with_items:
    - minikube
    - helm
    - stern
    - kubectl
    - k9s
  args:
    creates: /home/{{ lookup('env', 'USER') }}/.arkade/bin/{{ item }}
- name: Install cloud packages
  aur:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: aur_builder
  with_items:
    - tfenv
- name: Make sure we have a 'tfenv' group
  group:
    name: tfenv
    state: present
- name: Add user '{{ lookup('env', 'USER') }}' to 'tfenv'
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - tfenv
    append: yes
  become: true
