- name: Install arkade
  shell: >
    curl -sLS https://dl.get-arkade.dev | sudo sh
  become: yes
  become_user: aur_builder
  args:
    creates: "/usr/local/bin/arkade"
- name: "Install ark packages version {{ item }}"
  shell: >
    ark get {{ item }}
  with_items:
  - minikube
  - helm
  - stern
  - kubectl
  - k9s
  args:
    creates: /home/{{ create_user }}/.arkade/bin/{{ item }}
- name: Install cloud packages
  aur:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: aur_builder
  with_items:
  - tfenv
- name: Make sure we have a 'tfenv' group
  group:
    name: tfenv
    state: present
- name: Add user '{{ create_user }}' to 'tfenv'
  user:
    name: "{{ create_user }}"
    groups:
    - tfenv
    append: yes
  become: true
- name: Install AWS CLI
  pip:
    name:
    - python-dateutil
    - jmespath
    - s3transfer
    - awscli
    extra_args: --user --upgrade