---
- name: install software
  hosts: localhost
  remote_user: kevin
  vars:
    system_packages:
      - albert
      - solaar
      - tilix
      - vlc
      - peek
      - gifski
      - ibus
      - ibus-unikey
    aur_packages:
      - google-chrome
      - antibody
    flatpak_packages:
      - com.spotify.Client
      - com.slack.Slack
  roles:
    - kewlfft.aur
    - users
    - cloud
    - common
    - ide
    - docker
    - python
    - node
    - zsh
    - aws
    # - gnome
    # - role: jaredhocutt.gnome_extensions
    #   vars:
    #     gnome_extension_ids:
    #     - 1723 # ShellTile
