---
- name: install software
  hosts: localhost
  remote_user: kevin
  vars:
    create_user: kevin
    system_packages:
    - albert
    - solaar
    - tilix
    - vlc
    - peek
    - gifski
    aur_packages:
    - google-chrome
    - antibody
    flatpak_packages:
    - com.spotify.Client
    - com.slack.Slack
  roles:
    - kewlfft.aur
    - cloud
    - users
    - common
    - gnome
    - ide
    - docker
    - python
    - role: jaredhocutt.gnome_extensions
      vars:
        gnome_extension_ids:
        - 1723 # ShellTile
    - node
    - zsh
