---
- name: install software
  hosts: localhost
  remote_user: kevin
  vars_files:
    - ./variables.yaml
  vars:
    system_packages:
      - albert
      - solaar
      - tilix
      - vlc
      - peek
      - gifski
      - ibus
      - ibus-unikey
      - neovim
    aur_packages:
      - google-chrome
      - postman-bin
    flatpak_packages:
      - com.spotify.Client
      - com.slack.Slack
  roles:
    - kewlfft.aur
    - users
    - initial
    - common
    - aws
    - cloud
    - ide
    - docker
    - python
    - node
    - zsh
    - gnome
    - role: jaredhocutt.gnome_extensions
      vars:
        gnome_extension_ids:
          - 1723 # ShellTile
