- name: Get stat of miniconda installation
  stat:
    path: /home/{{ lookup('env', 'USER') }}/miniconda3
  register: miniconda_stat
- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /home/{{ lookup('env', 'USER') }}/miniconda.sh
        mode: 0550
    - name: Run the installer
      shell: /home/{{ lookup('env', 'USER') }}/miniconda.sh -b -u -p /home/{{ lookup('env', 'USER') }}/miniconda3
    - name: Remove the installer
      file:
        state: absent
        path: /home/{{ lookup('env', 'USER') }}/miniconda.sh
  when: miniconda_stat.stat.isdir is not defined
