- name: Install AWS CLI
  shell: >
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install --update && \
    rm -rf awscliv2.zip && \
    rm -rf ./aws
  args:
    creates: /usr/local/bin/aws
  become: true
- name: Install AWS Credentials
  block:
    - name: Ensure ~/.aws folder exists
      file: 
        path: "/home/{{ lookup('env', 'USER') }}/.aws"
        state: directory
    - name: Install ~/.aws/config file
      ansible.builtin.template:
        src: awsconfig.j2
        dest: "/home/{{ lookup('env', 'USER') }}/.aws/config"
    - name: Install ~/.aws/credentials file
      ansible.builtin.template:
        src: awscredentials.j2
        dest: "/home/{{ lookup('env', 'USER') }}/.aws/credentials"
- name: Install Refresh MFA Script Utility
  ansible.builtin.copy:
    src: refresh-aws-mfa.py
    dest: /usr/local/bin/refresh-aws-mfa
    mode: 0755
  become: true
