---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: true
- name: Add user '{{ lookup('env', 'USER') }}' to 'wheel'
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - wheel
    append: yes
  become: true
