---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true
- name: Add user '{{ create_user }}' to 'wheel'
  user:
    name: "{{ create_user }}"
    groups:
    - wheel
    append: yes
  become: true
- include_tasks: aur.yml