- name: Install common packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  become: true
  loop: "{{ system_packages }}"
- name: Install AUR packages
  aur:
    name: "{{ item }}"
    state: latest
  loop: "{{ aur_packages }}"
- name: Install flatpak packages
  block:
  - name: Ensure flatpak is installed
    community.general.pacman:
      name: flatpak
      state: latest
  - name: Install flatpak packages
    community.general.flatpak:
      name: "{{ item }}"
      state: present
    become: true
    loop: "{{ flatpak_packages }}"