- name: Install Docker and Docker Compose
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - docker
    - docker-compose
- name: Start 'docker' service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

# Allow user to run docker without sudo
- name: Ensure 'docker' group exists
  group:
    name: docker
    state: present
- name: Add {{ lookup('env', 'USER') }} to 'docker' group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - docker
    append: yes
  become: true
