- name: Install Intellij IDEA
  block:
    - name: Install Intellij IDEA Ultimate Edition
      aur:
        name:
          - intellij-idea-ultimate-edition
          - intellij-idea-ultimate-edition-jre
        state: latest
    # Allow usage of nvm and conda in Intellij IDEA
    - name: Add ZSH-Enabled Intellij IDEA to desktop
      copy:
        src: "{{ role_path }}/files/intellij-idea.desktop"
        dest: "/home/{{ lookup('env', 'USER') }}/.local/share/applications/intellij-idea.desktop"
        mode: 0644
- name: Install VS Code
  aur:
    name: visual-studio-code-bin
    state: latest
